#!/bin/sh

# $Id: login.ini,v 1.2 2005/08/13 10:02:16 thomasez Exp $

if [ "$1" != "start" -a "$1" != "restart" ]
 then
  exit 0
fi

echo "Setting password for root"

#
# The "How to set up login" - file.
#
. /etc/ffw4.conf

#
# The file to play with.
#
PW_F=/etc/passwd

if [ "$PASSWORD" != "" ]
 then
  DES_PASSWORD=`cryptpw -a des $PASSWORD`
fi

# Right now, all we do it handle the DES_PASSWORD correctly:
sed -i -e "s|^root:x:|root:$DES_PASSWORD:|" $PW_F
sed -i -e "s|^root:x:|root:$DES_PASSWORD:|" /etc/shadow

sed -i -e "s:^PASSWORD.*::" /etc/ffw4.conf

