#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
 	echo "Starting network..."
    if [ -f /etc/network.init ]
     then
      /etc/network.init
     else
	  /sbin/ifup -a
    fi
	;;
  stop)
	echo -n "Stopping network..."
    if [ -f /etc/network.init ]
     then
      # No downscripts yet.. Not that it makes any sense at all.
      # /etc/network.init
      true
     else
      /sbin/ifdown -a
    fi
    ;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

